language: scala

env:
  - HBASE_VERSION=1.2.4

cache:
  directories:
  - $HOME/hbase-$HBASE_VERSION

scala:
  - 2.11.8

jdk:
  - oraclejdk8

sbt_args: -J-Xmx4G -J-Xms2G -J-Xss1M

before_install:
  - .travis/install-hbase.sh

before_script:
  - $HOME/hbase-$HBASE_VERSION/bin/start-hbase.sh
