language: scala

env:
  - HBASE_VERSION=1.2.4

cache:
  directories:
  - $HOME/hbase

scala:
  - 2.11.8

jdk:
  - oraclejdk8

sbt_args: -J-Xmx4G -J-Xms2G -J-Xss1M

before_script:
  - .travis/install-hbase.sh
  - $HOME/hbase/bin/start-hbase.sh
